// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTTNgoaiNgu.Data;

#nullable disable

namespace QuanLyTTNgoaiNgu.Migrations
{
    [DbContext(typeof(QuanLyTTNgoaiNguContext))]
    partial class QuanLyTTNgoaiNguContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("GIANGVIEN");

                    b.HasData(
                        new
                        {
                            MaGiangVien = 1,
                            ChuyenMon = "Tiếng Anh",
                            Email = "anhgv@gmail.com",
                            HoTen = "Nguyễn Minh Anh",
                            MaTaiKhoan = 6,
                            SoDienThoai = "0911222333"
                        },
                        new
                        {
                            MaGiangVien = 2,
                            ChuyenMon = "Tiếng Nhật",
                            Email = "hajp@gmail.com",
                            HoTen = "Trần Nhật Hạ",
                            MaTaiKhoan = 7,
                            SoDienThoai = "0911333444"
                        },
                        new
                        {
                            MaGiangVien = 3,
                            ChuyenMon = "Tiếng Hàn",
                            Email = "hoakr@gmail.com",
                            HoTen = "Lê Thị Hoa",
                            MaTaiKhoan = 8,
                            SoDienThoai = "0911444555"
                        },
                        new
                        {
                            MaGiangVien = 4,
                            ChuyenMon = "Tiếng Trung",
                            Email = "trungcn@gmail.com",
                            HoTen = "Phạm Quốc Trung",
                            MaTaiKhoan = 9,
                            SoDienThoai = "0911555666"
                        },
                        new
                        {
                            MaGiangVien = 5,
                            ChuyenMon = "Tiếng Pháp",
                            Email = "phapfr@gmail.com",
                            HoTen = "Vũ Thanh Pháp",
                            MaTaiKhoan = 10,
                            SoDienThoai = "0911666777"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCPHI", b =>
                {
                    b.Property<int>("MaHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhi"));

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHocPhi");

                    b.HasIndex("MaDangKy")
                        .IsUnique();

                    b.ToTable("HOCPHI");

                    b.HasData(
                        new
                        {
                            MaHocPhi = 1,
                            MaDangKy = 1,
                            NgayNop = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 2,
                            MaDangKy = 2,
                            NgayNop = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 3,
                            MaDangKy = 3,
                            TrangThai = false
                        },
                        new
                        {
                            MaHocPhi = 4,
                            MaDangKy = 4,
                            NgayNop = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 5,
                            MaDangKy = 5,
                            TrangThai = false
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TAIKHOANMaTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("MaHocVien");

                    b.HasIndex("TAIKHOANMaTaiKhoan");

                    b.ToTable("HOCVIEN");

                    b.HasData(
                        new
                        {
                            MaHocVien = 1,
                            DiaChi = "Hà Nội",
                            Email = "nhung@gmail.com",
                            HoTen = "Trần Hồng Nhung",
                            MaTaiKhoan = 1,
                            NgaySinh = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0931222333"
                        },
                        new
                        {
                            MaHocVien = 2,
                            DiaChi = "Đà Nẵng",
                            Email = "long@gmail.com",
                            HoTen = "Ngô Đức Long",
                            MaTaiKhoan = 2,
                            NgaySinh = new DateTime(2002, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0931333444"
                        },
                        new
                        {
                            MaHocVien = 3,
                            DiaChi = "TP.HCM",
                            Email = "thu@gmail.com",
                            HoTen = "Vũ Thị Thu",
                            MaTaiKhoan = 3,
                            NgaySinh = new DateTime(2001, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0931444555"
                        },
                        new
                        {
                            MaHocVien = 4,
                            DiaChi = "Hải Phòng",
                            Email = "nam@gmail.com",
                            HoTen = "Lê Văn Nam",
                            MaTaiKhoan = 4,
                            NgaySinh = new DateTime(2000, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0931555666"
                        },
                        new
                        {
                            MaHocVien = 5,
                            DiaChi = "Cần Thơ",
                            Email = "mai@gmail.com",
                            HoTen = "Phạm Thị Mai",
                            MaTaiKhoan = 5,
                            NgaySinh = new DateTime(2004, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0931666777"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KETQUAHOCTAP", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<float>("ChuyenCan")
                        .HasColumnType("real");

                    b.Property<float>("Diem")
                        .HasColumnType("real");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("KETQUAHOCTAP");

                    b.HasData(
                        new
                        {
                            MaKetQua = 1,
                            ChuyenCan = 9f,
                            Diem = 8f,
                            MaHocVien = 1,
                            MaLopHoc = 1
                        },
                        new
                        {
                            MaKetQua = 2,
                            ChuyenCan = 8.5f,
                            Diem = 7.5f,
                            MaHocVien = 2,
                            MaLopHoc = 2
                        },
                        new
                        {
                            MaKetQua = 3,
                            ChuyenCan = 9.5f,
                            Diem = 9f,
                            MaHocVien = 3,
                            MaLopHoc = 3
                        },
                        new
                        {
                            MaKetQua = 4,
                            ChuyenCan = 8f,
                            Diem = 7f,
                            MaHocVien = 4,
                            MaLopHoc = 4
                        },
                        new
                        {
                            MaKetQua = 5,
                            ChuyenCan = 9f,
                            Diem = 8.5f,
                            MaHocVien = 5,
                            MaLopHoc = 5
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KHOAHOC", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("MucHocPhi")
                        .HasColumnType("float");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KHOAHOC");

                    b.HasData(
                        new
                        {
                            MaKhoaHoc = 1,
                            MoTa = "Học giao tiếp tiếng Anh cơ bản",
                            MucHocPhi = 1500000.0,
                            TenKhoaHoc = "Tiếng Anh giao tiếp"
                        },
                        new
                        {
                            MaKhoaHoc = 2,
                            MoTa = "Học tiếng Nhật sơ cấp N5",
                            MucHocPhi = 1800000.0,
                            TenKhoaHoc = "Tiếng Nhật N5"
                        },
                        new
                        {
                            MaKhoaHoc = 3,
                            MoTa = "Học tiếng Hàn cho người mới bắt đầu",
                            MucHocPhi = 1700000.0,
                            TenKhoaHoc = "Tiếng Hàn sơ cấp"
                        },
                        new
                        {
                            MaKhoaHoc = 4,
                            MoTa = "Giao tiếp tiếng Trung cơ bản",
                            MucHocPhi = 1600000.0,
                            TenKhoaHoc = "Tiếng Trung giao tiếp"
                        },
                        new
                        {
                            MaKhoaHoc = 5,
                            MoTa = "Tiếng Pháp cho người bắt đầu",
                            MucHocPhi = 1900000.0,
                            TenKhoaHoc = "Tiếng Pháp A1"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<DateTime>("LichHoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LOPHOC");

                    b.HasData(
                        new
                        {
                            MaLopHoc = 1,
                            LichHoc = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaGiangVien = 1,
                            MaKhoaHoc = 1,
                            TenLop = "Anh Giao Tiep 101"
                        },
                        new
                        {
                            MaLopHoc = 2,
                            LichHoc = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaGiangVien = 2,
                            MaKhoaHoc = 2,
                            TenLop = "Nhat N5 Sáng"
                        },
                        new
                        {
                            MaLopHoc = 3,
                            LichHoc = new DateTime(2025, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaGiangVien = 3,
                            MaKhoaHoc = 3,
                            TenLop = "Han Sơ Cấp 1"
                        },
                        new
                        {
                            MaLopHoc = 4,
                            LichHoc = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaGiangVien = 4,
                            MaKhoaHoc = 4,
                            TenLop = "Trung Giao Tiep 1"
                        },
                        new
                        {
                            MaLopHoc = 5,
                            LichHoc = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaGiangVien = 5,
                            MaKhoaHoc = 5,
                            TenLop = "Phap A1 Tối"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("PHIEUDANGKY");

                    b.HasData(
                        new
                        {
                            MaDangKy = 1,
                            MaHocVien = 1,
                            MaLopHoc = 1,
                            NgayDangKy = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaDangKy = 2,
                            MaHocVien = 2,
                            MaLopHoc = 2,
                            NgayDangKy = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaDangKy = 3,
                            MaHocVien = 3,
                            MaLopHoc = 3,
                            NgayDangKy = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaDangKy = 4,
                            MaHocVien = 4,
                            MaLopHoc = 4,
                            NgayDangKy = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaDangKy = 5,
                            MaHocVien = 5,
                            MaLopHoc = 5,
                            NgayDangKy = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.QUANTRIVIEN", b =>
                {
                    b.Property<int>("MaQuanTriVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuanTriVien"));

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int?>("TAIKHOANSMaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanTriVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaQuanTriVien");

                    b.HasIndex("TAIKHOANSMaTaiKhoan");

                    b.ToTable("QUANTRIVIEN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.TAIKHOAN", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TAIKHOAN");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien1",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien2",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien3",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 4,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien4",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 5,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien5",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 6,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien1",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 7,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien2",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 8,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien3",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 9,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien4",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 10,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien5",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 11,
                            MatKhau = "admin123",
                            TenDangNhap = "admin1",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 12,
                            MatKhau = "admin123",
                            TenDangNhap = "admin2",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 13,
                            MatKhau = "admin123",
                            TenDangNhap = "admin3",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 14,
                            MatKhau = "admin123",
                            TenDangNhap = "admin4",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 15,
                            MatKhau = "admin123",
                            TenDangNhap = "admin5",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TAIKHOAN")
                        .WithMany("GIANGVIENs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCPHI", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", "PHIEUDANGKY")
                        .WithOne("HOCPHI")
                        .HasForeignKey("QuanLyTTNgoaiNgu.Models.HOCPHI", "MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PHIEUDANGKY");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", null)
                        .WithMany("HOCVIENs")
                        .HasForeignKey("TAIKHOANMaTaiKhoan");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KETQUAHOCTAP", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.HOCVIEN", "HOCVIEN")
                        .WithMany("KETQUAHOCTAPs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.LOPHOC", "LOPHOC")
                        .WithMany("KETQUAHOCTAPs")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HOCVIEN");

                    b.Navigation("LOPHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.GIANGVIEN", "GIANGVIEN")
                        .WithMany("LOPHOCs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.KHOAHOC", "KHOAHOC")
                        .WithMany("LOPHOCs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GIANGVIEN");

                    b.Navigation("KHOAHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.HOCVIEN", "HOCVIEN")
                        .WithMany("PHIEUDANGKYs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.LOPHOC", "LOPHOC")
                        .WithMany("PHIEUDANGKYs")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HOCVIEN");

                    b.Navigation("LOPHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.QUANTRIVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TAIKHOANS")
                        .WithMany("QUANTRIVIENs")
                        .HasForeignKey("TAIKHOANSMaTaiKhoan");

                    b.Navigation("TAIKHOANS");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.Navigation("LOPHOCs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.Navigation("KETQUAHOCTAPs");

                    b.Navigation("PHIEUDANGKYs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KHOAHOC", b =>
                {
                    b.Navigation("LOPHOCs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.Navigation("KETQUAHOCTAPs");

                    b.Navigation("PHIEUDANGKYs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.Navigation("HOCPHI");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.TAIKHOAN", b =>
                {
                    b.Navigation("GIANGVIENs");

                    b.Navigation("HOCVIENs");

                    b.Navigation("QUANTRIVIENs");
                });
#pragma warning restore 612, 618
        }
    }
}
